<img src="https://raw.githubusercontent.com/toqafotoh/TeamPreparation/main/Blue%20and%20Yellow%20Playful%20Doodle%20Digital%20Brainstorm%20Presentation.png">

<span style="color: #8f3b43; font-size: 35px;">Useless Note 🙈</span>
#### The name "NumPy" is short for "Numerical Python."

In [5]:
#imorting the library to work with
import numpy as np

In [9]:
#the simplist and first way to create numpy array
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)
#as we see the type isn't list, and even when printing it , it's preceded by the word array

numpy.ndarray

In [13]:
#you can create it with passing alist, tuple,set to this fuction
arr = np.array((1, 2, 3, 4, 5))
arr

array([1, 2, 3, 4, 5])

In [14]:
'''
or create it with the function "arange"
it can take a number and make you an array from 1 to it 
or take a start point , ending point and step .. as range function
'''
arr1 = np.arange(1000000)
arr2 = np.arange(1,50,2)
print(arr1)
print(arr2)


[     0      1      2 ... 999997 999998 999999]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [30]:
arr = np.linspace(0, 1, 11, endpoint=True)
arr
#linspace is different that the third argument is the number of elements 


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

endpoint here is an argument that determine whether the ending value in included or not <br/>
<span style="color: #8f3b43; font-size: 35px;">✨NOTE :</span><br/>
<span style="color: blue; font-size: 20px;">you can check the documentation of any function to see its arguments and their importance by typing "function name"+"?"</span>

In [31]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

<span style="color: #8f3b43; font-size: 25px;">Special types of arrays</span>

In [17]:
# zeros and ones functions create a 1 dimentional array of n elements
zeros_array = np.zeros(5) #olny zeros array
ones_array = np.ones(3) #only ones array
# eye is a function that makes 2D identity matrix of n*n 
identity_matrix = np.eye(3) 
print(zeros_array)
print(ones_array)
print(identity_matrix)

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
def condition(x,y):
    return x+y
toto = np.fromfunction(condition, (3, 3))
toto


array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [26]:
'''
the previous function is creating an array of 3 cols & 3 rows 
and it has the numbers from 0 to 2 for x and y
as x  = 3 numbers and y = 3 numbers 
x = [0,1,2]
y= [0,1,2]
it makes all the combinations between them and pass that to the function that you wrote
'''

'''
Iterations
When x=0 and y=0, the function condition(0, 0) is called.
When x=0 and y=1, the function condition(0, 1) is called.
When x=0 and y=2, the function condition(0, 2) is called.
When x=1 and y=0, the function condition(1, 0) is called.
When x=1 and y=1, the function condition(1, 1) is called.
When x=1 and y=2, the function condition(1, 2) is called.
When x=2 and y=0, the function condition(2, 0) is called.
When x=2 and y=1, the function condition(2, 1) is called.
When x=2 and y=2, the function condition(2, 2) is called.
'''


'\nIterations\nWhen x=0 and y=0, the function condition(0, 0) is called.\nWhen x=0 and y=1, the function condition(0, 1) is called.\nWhen x=0 and y=2, the function condition(0, 2) is called.\nWhen x=1 and y=0, the function condition(1, 0) is called.\nWhen x=1 and y=1, the function condition(1, 1) is called.\nWhen x=1 and y=2, the function condition(1, 2) is called.\nWhen x=2 and y=0, the function condition(2, 0) is called.\nWhen x=2 and y=1, the function condition(2, 1) is called.\nWhen x=2 and y=2, the function condition(2, 2) is called.\n'

<span style="color: #8f3b43; font-size: 25px;">Multidimensional Array</span>